markdown: kramdown
theme: minima
title: "NeuroSTA Lab"
description: "Neuroimaging and Speech using Transdiagnostic Approaches"
# Navigation links
header_pages:
  - index.md
  - people.md
  - research.md
  - publications.md
  - contact.md
