include: ["assets/css/custom.css"]
title: "NeuroSTA"
description: "Neuroimaging and Speech using Transdiagnostic Approaches"
theme: minima
markdown: kramdown

# Seiten für das Header-Menü
header_pages:
  - index.md
  - people.md
  - research.md
  - publications.md
  - contact.md

# eigene CSS-Datei einbinden
sass:
  style: compressed

# assets/css/custom.css wird automatisch übernommen
